import Head from 'next/head'
import { Inter } from 'next/font/google'
import {
    Anchor,
    Badge,
    Box,
    Button,
    Card,
    Center,
    Group,
    Space,
    Stack,
    Text,
    Image,
    ActionIcon,
    MediaQuery
} from "@mantine/core";
import {Icon2fa, IconDownload, IconCircleArrowRight, IconBrandInstagram,IconBrandGithub} from "@tabler/icons-react";
import Link from "next/link";
const inter = Inter({ subsets: ['latin'] })

    export default function Home() {
    function openPage(page:string) {
        window.location.href = page;
    }

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Box w='100%' h='40vh' bg='brand.0' style={{borderRadius: '24px'}} pl={'2%'} pr={'2%'} mb={'4vh'}>
            <Group position='apart'>
                <Center h='40vh'>
                    <Stack spacing={0}>
                        <Center display={{base: 'block', lg:'none'}}>
                            <Box w='150px' h='150px' bg='black' style={{borderRadius: '50%', overflow: 'hidden'}}>
                                <Center h='150px'>
                                    <Image fit='cover' src="/modLogo.png" alt="logo modularify" />
                                </Center>
                            </Box>
                        </Center>
                        <Text fz={{base: '4rem', lg:'10rem'}} fw={300} color='white.3'>Modularify - </Text>
                        <Group pl={'1%'}>
                            <Text fz={'1.5rem'} fw={300} color='white.3'>modularify@gmail.com </Text>
                            <ActionIcon variant="transparent" onClick={() =>{openPage("https://github.com/modularify")}}>
                                <IconBrandGithub color={'white'} size="1.5rem" />
                            </ActionIcon>
                            <ActionIcon variant="transparent" onClick={() =>{openPage("https://www.instagram.com/modularify_unity/")}}>
                                <IconBrandInstagram color={'white'} size="1.5rem" />
                            </ActionIcon>
                        </Group>
                    </Stack>
                 </Center>
                <Center display={{base: 'none', lg:'block'}}>
                    <Box w='250px' h='250px' bg='black' style={{borderRadius: '50%', overflow: 'hidden'}}>
                        <Center h='240px'>
                            <Image fit='cover' src="/modLogo.png" alt="logo modularify" />
                        </Center>
                    </Box>
                </Center>
            </Group>
       </Box>
        <Box w='100%' h='40vh' style={{borderRadius: '24px'}}>
            <Group position='apart'>
                <Box w={{base: '100%', lg:'30%'}} h={{base:'20vh', lg:'40vh'}} bg='brand.1' style={{borderRadius: '24px',  cursor:'pointer'}} pl={'2%'} pr={'2%'} onClick={() =>{openPage('/about-me')}}>
                    <Center h={{base:'19vh', lg:'39vh'}}>
                        <Text fz={{base: '4rem', lg:'8rem'}} fw={300} color='white.3'>About me </Text>
                    </Center>
                </Box>
                <Box w={{base: '100%', lg:'68%'}}  h={{base:'20vh', lg:'40vh'}} bg='#ADB5BD' style={{borderRadius: '24px', cursor:'pointer'}} pl={'2%'} pr={'2%'} onClick={() =>{openPage('/projects')}}>
                    <MediaQuery smallerThan="lg" styles={{ display: 'none' }}>
                        <Group position='apart'>
                            <Center h={{base:'19vh', lg:'35vh'}}>
                                <Text fz={{base: '4rem', lg:'10rem'}} fw={300} color='white.3'>Projects </Text>
                            </Center>
                            <Center h={{base:'19vh', lg:'37vh'}}>
                                <IconCircleArrowRight color={'#DEE2E6'} size={'15rem'}/>
                            </Center>
                        </Group>
                    </MediaQuery>
                    <MediaQuery largerThan="lg" styles={{ display: 'none' }}>
                        <Center h={{base:'19vh', lg:'39vh'}}>
                            <Text fz={{base: '4rem', lg:'10rem'}} fw={300} color='white.3'>Projects </Text>
                        </Center>
                    </MediaQuery>

                </Box>
            </Group>

        </Box>
    </Box>
  )
}
